In [9]:
import numpy as np
import pandas as pd

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# create array from list
avo = [1,3,4,6,3]
np.array(avo)

# all trues 3x3 array
all_true = np.full((3,3), True, dtype=bool)

# extract odd numbers from arr
odd_num = arr[arr % 2 == 1]

# replace all odd numbser from arr with -1 
arr[arr % 2 == 1] = -1

In [25]:
# replacec without changing og array 
out = np.where(arr%2 == 1, -1, arr)   # if condition then a else b 

# reshape 1D into 2D with 2 rows
a = np.arange(10)
a = a.reshape(2,-1)

# stack arrays a and b 
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a, b))

np.hstack((a, b))


# repeat a pattern
c = np.array([1,2,3])
np.r_[(np.repeat(c,3), np.tile(c,3))] #Translates slice objects to concatenation along the first axis.

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#find common items between a and b 

c = np.intersect1d(a, b)

# delete all items from a present in b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

# get position of matching elements 
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

# get all num between 5 and 10 
np.where((a<=5) & (a>= 10))

np.zeros(a.size)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
# function to do elementwise comparision and return the bigger value
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# either
np.maximum(a, b)

# or
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

# swap two columns in 3d array
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1,0,2]]

# swap two rows
arr[[1,0,2],:]

# flip the rows
np.flip(arr, axis=1)
#or
arr[::-1]

#reverse cols 
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [64]:
# create 2D, 5 x 3  array with rand numbers between 5 and 10 
rand_arr = np.random.uniform(5, 10, size=(5,3))